### ISSUE TITLE
plotting the trajectory in python

### ISSUE THREAD

**Issue by Iko-Git** [icsl-Jeon/traj_gen#8]
Dear Authors,

I'd like to kindly ask, how can I see the generated trajectories in Colab.
I am performing:
`!python3 /content/traj_gen/python/scripts/poly_3d_example.py`
and the trajectory is shown as the following info, not as image, gif, or other visual extension:
`<Figure size 640x480 with 15 Axes>`
Any support would be highly appreciated.

**Comment by icsl-Jeon** [comment]
Hello @tomcattigerkkk , could you respond to this issue? thank you :)

**Comment by Iko-Git** [comment]
@tomcattigerkkk support would be highly appreciated

**Comment by tomcattiger1230** [comment]
Hi,
sorry for the response delay @icsl-Jeon @Iko-Git .
I don't have much experience with Colab. I will test today. But I think it is the issue using colab. Have you ever tried with norm terminal on your local machine

**Comment by tomcattiger1230** [comment]
Hi @Iko-Git 

I searched online. And I can confirm that the issue is caused by directly run python scripts with matplotlib in colab. I've not found any good solution currently. However, you can copy all codes in colab with an additional line (same for the jupyter notebook)
`%matplotlib inline`
It should be able to plot the figure. If you want, you can also modify the plot function, so that it dose not plot the figure directly, but save it as png file.

**Comment by tomcattiger1230** [comment]
Hi, 
@icsl-Jeon @Iko-Git 
I think you can use 
`%run ` instead of `!python` 
to run the script. It should work now. Note that I also use some latex format in plot. You need to install latex environment in colab

**Comment by Iko-Git** [comment]
It got solved by performing the following installation 
`!apt install pdfTeX`
`!apt install texlive-full`
`!apt install texmaker`
